#!/usr/bin/env bash

node dev/build.js

yarn wpcs:fix

ROOTDIR=$(pwd)
NAME="palacify"
VERSION=$(php -r 'preg_match("/\*\s?Version\:\s?(.*?)\n/i", file_get_contents("./palacify.php"), $m);echo is_array($m) && isset($m[1]) ? $m[1] : "";')
FOLDER="$NAME"
ZIPNAME="$NAME-$VERSION.zip";
TMPDIRNAME="glkHjfgjJUghufgKIolf"

if [ -d "$TMPDIRNAME" ]; then
    rm -rf $TMPDIRNAME
fi

if [ -f "$ZIPNAME" ]; then
    rm $ZIPNAME
fi

zip -q -r "$ZIPNAME" . -x \
    "scripts/*" \
    "vendor/*" \
    "*.log" \
    "*.zip" \
    ".gitignore" \
    "composer.json" \
    "composer.lock" \
    "package.json" \
    "*.md" \
    "phpcs.xml" \
    ".git/*" \
    yarn.lock \
    "node_modules/*" \
    "dev/*" \
    "mods/html-blocks/src/*" \
    nodemon.json \
    "*.map" \
    "svn/*"


mkdir $TMPDIRNAME
mkdir "$TMPDIRNAME/$FOLDER"
mv $ZIPNAME "$TMPDIRNAME/$FOLDER/"
cd "$TMPDIRNAME/$FOLDER/"
unzip -q $ZIPNAME
rm $ZIPNAME
cd ../
zip -q -r $ZIPNAME $FOLDER
mv $ZIPNAME ../
cd ../
rm -rf $TMPDIRNAME