#!/usr/bin/env bash

NAME="palacify"
VERSION=$(php -r 'preg_match("/\*\s?Version\:\s?(.*?)\n/i", file_get_contents("./palacify.php"), $m);echo is_array($m) && isset($m[1]) ? $m[1] : "";')
FOLDER="$NAME"
ZIPNAME="$NAME-$VERSION.zip";

yarn release

if [ -d "svn" ]; then
    rm -rf ./svn
fi

mkdir svn

svn co https://plugins.svn.wordpress.org/palacify/ svn

if [ -d "svn/tags/$VERSION" ]; then
    rm -rf svn/tags/$VERSION
fi

mkdir svn/tags/$VERSION

rm -rf ./svn/trunk/*

unzip -q $ZIPNAME -d ./svn/trunk
mv ./svn/trunk/$NAME/* ./svn/trunk/
rmdir ./svn/trunk/$NAME/

unzip -q $ZIPNAME -d svn/tags/$VERSION
mv svn/tags/$VERSION/$NAME/* svn/tags/$VERSION/
rmdir svn/tags/$VERSION/$NAME/

cd svn

svn stat